#https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
name: debug

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get commit message
        run: |
          {
            echo 'LAST_COMMIT_MESSAGE<<EOF'
            if [ "${{ github.event_name }}" == "push" ]; then
              echo "${{ github.event.head_commit.message }}"
            elif [ "${{ github.event_name }}" == "workflow_run" ]; then
              echo "${{ github.event.workflow_run.head_commit.message }}"
            elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
              COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.sha }}|")
              echo "$(curl -s "$COMMIT_URL" | jq -r '.commit.message')"
            elif [ "${{ github.event_name }}" == "pull_request" ]; then
              PR_COMMIT_URL=$(echo "${{ github.event.repository.commits_url }}" | sed "s|{/sha}|/${{ github.event.pull_request.head.sha }}|")
              echo "$(curl -s "$PR_COMMIT_URL" | jq -r '.commit.message')"
            fi
            echo EOF
          } | tee -a $GITHUB_ENV
